# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/released-ci/released_ci.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2
from bk_bscp.grpc_lib.core.commit import commit_pb2 as pkg_dot_protocol_dot_core_dot_commit_dot_commit__pb2
from bk_bscp.grpc_lib.core.config_item import config_item_pb2 as pkg_dot_protocol_dot_core_dot_config__item_dot_config__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/pkg/protocol/core/released-ci/released_ci.proto\x12\x05pbrci\x1a!pkg/protocol/core/base/base.proto\x1a%pkg/protocol/core/commit/commit.proto\x1a/pkg/protocol/core/config-item/config_item.proto\"\x8a\x02\n\x12ReleasedConfigItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x12\n\nrelease_id\x18\x02 \x01(\r\x12\x11\n\tcommit_id\x18\x03 \x01(\r\x12\x31\n\x0b\x63ommit_spec\x18\x04 \x01(\x0b\x32\x1c.pbcommit.ReleasedCommitSpec\x12\x16\n\x0e\x63onfig_item_id\x18\x05 \x01(\r\x12\"\n\x04spec\x18\x06 \x01(\x0b\x32\x14.pbci.ConfigItemSpec\x12.\n\nattachment\x18\x07 \x01(\x0b\x32\x1a.pbci.ConfigItemAttachment\x12\"\n\x08revision\x18\x08 \x01(\x0b\x32\x10.pbbase.RevisionB]Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/released-ci;pbrcib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.released_ci.released_ci_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/released-ci;pbrci'
  _globals['_RELEASEDCONFIGITEM']._serialized_start=182
  _globals['_RELEASEDCONFIGITEM']._serialized_end=448
# @@protoc_insertion_point(module_scope)
