# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/app-template-variable/app_template_variable.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2
from bk_bscp.grpc_lib.core.template_variable import template_variable_pb2 as pkg_dot_protocol_dot_core_dot_template__variable_dot_template__variable__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCpkg/protocol/core/app-template-variable/app_template_variable.proto\x12\x05pbatv\x1a!pkg/protocol/core/base/base.proto\x1a;pkg/protocol/core/template-variable/template_variable.proto\"\xad\x01\n\x13\x41ppTemplateVariable\x12\n\n\x02id\x18\x01 \x01(\r\x12,\n\x04spec\x18\x02 \x01(\x0b\x32\x1e.pbatv.AppTemplateVariableSpec\x12\x38\n\nattachment\x18\x03 \x01(\x0b\x32$.pbatv.AppTemplateVariableAttachment\x12\"\n\x08revision\x18\x04 \x01(\x0b\x32\x10.pbbase.Revision\"H\n\x17\x41ppTemplateVariableSpec\x12-\n\tvariables\x18\x01 \x03(\x0b\x32\x1a.pbtv.TemplateVariableSpec\"?\n\x1d\x41ppTemplateVariableAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\r\"\xcb\x01\n\x1c\x41ppTemplateVariableReference\x12\x15\n\rvariable_name\x18\x01 \x01(\t\x12\x41\n\nreferences\x18\x02 \x03(\x0b\x32-.pbatv.AppTemplateVariableReference.reference\x1aQ\n\treference\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1c\n\x14template_revision_id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\tBgZegithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/app-template-variable;pbatvb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.app_template_variable.app_template_variable_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zegithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/app-template-variable;pbatv'
  _globals['_APPTEMPLATEVARIABLE']._serialized_start=175
  _globals['_APPTEMPLATEVARIABLE']._serialized_end=348
  _globals['_APPTEMPLATEVARIABLESPEC']._serialized_start=350
  _globals['_APPTEMPLATEVARIABLESPEC']._serialized_end=422
  _globals['_APPTEMPLATEVARIABLEATTACHMENT']._serialized_start=424
  _globals['_APPTEMPLATEVARIABLEATTACHMENT']._serialized_end=487
  _globals['_APPTEMPLATEVARIABLEREFERENCE']._serialized_start=490
  _globals['_APPTEMPLATEVARIABLEREFERENCE']._serialized_end=693
  _globals['_APPTEMPLATEVARIABLEREFERENCE_REFERENCE']._serialized_start=612
  _globals['_APPTEMPLATEVARIABLEREFERENCE_REFERENCE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
