# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/released-group/released_group.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5pkg/protocol/core/released-group/released_group.proto\x12\x04pbrg\"\x86\x01\n\rReleasedGroup\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08group_id\x18\x02 \x01(\r\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\r\x12\x12\n\nrelease_id\x18\x04 \x01(\r\x12\x13\n\x0bstrategy_id\x18\x05 \x01(\r\x12\x0e\n\x06\x65\x64ited\x18\x06 \x01(\x08\x12\x0e\n\x06\x62iz_id\x18\x07 \x01(\rB_Z]github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/released-group;pbrgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.released_group.released_group_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z]github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/released-group;pbrg'
  _globals['_RELEASEDGROUP']._serialized_start=64
  _globals['_RELEASEDGROUP']._serialized_end=198
# @@protoc_insertion_point(module_scope)
