# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/client-event/client_event.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1pkg/protocol/core/client-event/client_event.proto\x12\x04pbce\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n\x0b\x43lientEvent\x12\n\n\x02id\x18\x01 \x01(\r\x12#\n\x04spec\x18\x02 \x01(\x0b\x32\x15.pbce.ClientEventSpec\x12/\n\nattachment\x18\x03 \x01(\x0b\x32\x1b.pbce.ClientEventAttachment\x12\x32\n\x0eheartbeat_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cmessage_type\x18\x05 \x01(\t\x12\x1d\n\x15original_release_name\x18\x06 \x01(\t\x12\x1b\n\x13target_release_name\x18\x07 \x01(\t\"\xa9\x03\n\x0f\x43lientEventSpec\x12\x1b\n\x13original_release_id\x18\x01 \x01(\r\x12\x19\n\x11target_release_id\x18\x02 \x01(\r\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rtotal_seconds\x18\x05 \x01(\x01\x12\x17\n\x0ftotal_file_size\x18\x06 \x01(\x01\x12\x1a\n\x12\x64ownload_file_size\x18\x07 \x01(\x01\x12\x16\n\x0etotal_file_num\x18\x08 \x01(\r\x12\x19\n\x11\x64ownload_file_num\x18\t \x01(\r\x12\x1d\n\x15release_change_status\x18\n \x01(\t\x12$\n\x1crelease_change_failed_reason\x18\x0b \x01(\t\x12\x1c\n\x14\x66\x61iled_detail_reason\x18\x0c \x01(\t\x12\x1e\n\x16specific_failed_reason\x18\r \x01(\t\"\x7f\n\x15\x43lientEventAttachment\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0e\n\x06\x62iz_id\x18\x03 \x01(\r\x12\x0e\n\x06\x61pp_id\x18\x04 \x01(\r\x12\x13\n\x0b\x63lient_mode\x18\x05 \x01(\t\x12\x11\n\tcursor_id\x18\x06 \x01(\tB]Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/client-event;pbceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.client_event.client_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/client-event;pbce'
  _globals['_CLIENTEVENT']._serialized_start=93
  _globals['_CLIENTEVENT']._serialized_end=338
  _globals['_CLIENTEVENTSPEC']._serialized_start=341
  _globals['_CLIENTEVENTSPEC']._serialized_end=766
  _globals['_CLIENTEVENTATTACHMENT']._serialized_start=768
  _globals['_CLIENTEVENTATTACHMENT']._serialized_end=895
# @@protoc_insertion_point(module_scope)
