# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/config-item/config_item.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2
from bk_bscp.grpc_lib.core.commit import commit_pb2 as pkg_dot_protocol_dot_core_dot_commit_dot_commit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/pkg/protocol/core/config-item/config_item.proto\x12\x04pbci\x1a!pkg/protocol/core/base/base.proto\x1a%pkg/protocol/core/commit/commit.proto\"\xe7\x01\n\nConfigItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x0e\x63onfig_item_id\x18\x02 \x01(\r\x12\x12\n\nfile_state\x18\x03 \x01(\t\x12\"\n\x04spec\x18\x04 \x01(\x0b\x32\x14.pbci.ConfigItemSpec\x12)\n\x0b\x63ommit_spec\x18\x05 \x01(\x0b\x32\x14.pbcommit.CommitSpec\x12.\n\nattachment\x18\x06 \x01(\x0b\x32\x1a.pbci.ConfigItemAttachment\x12\"\n\x08revision\x18\x07 \x01(\x0b\x32\x10.pbbase.Revision\"\x8a\x01\n\x0e\x43onfigItemSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x11\n\tfile_mode\x18\x04 \x01(\t\x12\x0c\n\x04memo\x18\x05 \x01(\t\x12(\n\npermission\x18\x06 \x01(\x0b\x32\x14.pbci.FilePermission\"6\n\x14\x43onfigItemAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\r\"E\n\x0e\x46ilePermission\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x12\n\nuser_group\x18\x02 \x01(\t\x12\x11\n\tprivilege\x18\x03 \x01(\t\"H\n\x14ListConfigItemCounts\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x11\n\tupdate_at\x18\x03 \x01(\tB\\ZZgithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/config-item;pbcib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.config_item.config_item_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZZgithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/config-item;pbci'
  _globals['_CONFIGITEM']._serialized_start=132
  _globals['_CONFIGITEM']._serialized_end=363
  _globals['_CONFIGITEMSPEC']._serialized_start=366
  _globals['_CONFIGITEMSPEC']._serialized_end=504
  _globals['_CONFIGITEMATTACHMENT']._serialized_start=506
  _globals['_CONFIGITEMATTACHMENT']._serialized_end=560
  _globals['_FILEPERMISSION']._serialized_start=562
  _globals['_FILEPERMISSION']._serialized_end=631
  _globals['_LISTCONFIGITEMCOUNTS']._serialized_start=633
  _globals['_LISTCONFIGITEMCOUNTS']._serialized_end=705
# @@protoc_insertion_point(module_scope)
