# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/template-revision/template_revision.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2
from bk_bscp.grpc_lib.core.config_item import config_item_pb2 as pkg_dot_protocol_dot_core_dot_config__item_dot_config__item__pb2
from bk_bscp.grpc_lib.core.content import content_pb2 as pkg_dot_protocol_dot_core_dot_content_dot_content__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;pkg/protocol/core/template-revision/template_revision.proto\x12\x04pbtr\x1a!pkg/protocol/core/base/base.proto\x1a/pkg/protocol/core/config-item/config_item.proto\x1a\'pkg/protocol/core/content/content.proto\"\xa9\x01\n\x10TemplateRevision\x12\n\n\x02id\x18\x01 \x01(\r\x12(\n\x04spec\x18\x02 \x01(\x0b\x32\x1a.pbtr.TemplateRevisionSpec\x12\x34\n\nattachment\x18\x03 \x01(\x0b\x32 .pbtr.TemplateRevisionAttachment\x12)\n\x08revision\x18\x04 \x01(\x0b\x32\x17.pbbase.CreatedRevision\"\xde\x01\n\x14TemplateRevisionSpec\x12\x15\n\rrevision_name\x18\x01 \x01(\t\x12\x15\n\rrevision_memo\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x11\n\tfile_type\x18\x05 \x01(\t\x12\x11\n\tfile_mode\x18\x06 \x01(\t\x12(\n\npermission\x18\x07 \x01(\x0b\x32\x14.pbci.FilePermission\x12,\n\x0c\x63ontent_spec\x18\x08 \x01(\x0b\x32\x16.pbcontent.ContentSpec\"\\\n\x1aTemplateRevisionAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x19\n\x11template_space_id\x18\x02 \x01(\r\x12\x13\n\x0btemplate_id\x18\x03 \x01(\r\"\xac\x02\n\x1bTemplateRevisionNamesDetail\x12\x13\n\x0btemplate_id\x18\x01 \x01(\r\x12\x15\n\rtemplate_name\x18\x02 \x01(\t\x12#\n\x1blatest_template_revision_id\x18\x03 \x01(\r\x12L\n\x12template_revisions\x18\x04 \x03(\x0b\x32\x30.pbtr.TemplateRevisionNamesDetail.revision_names\x1an\n\x0erevision_names\x12\x1c\n\x14template_revision_id\x18\x01 \x01(\r\x12\x1e\n\x16template_revision_name\x18\x02 \x01(\t\x12\x1e\n\x16template_revision_memo\x18\x03 \x01(\tBbZ`github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/template-revision;pbtrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.template_revision.template_revision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z`github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/template-revision;pbtr'
  _globals['_TEMPLATEREVISION']._serialized_start=195
  _globals['_TEMPLATEREVISION']._serialized_end=364
  _globals['_TEMPLATEREVISIONSPEC']._serialized_start=367
  _globals['_TEMPLATEREVISIONSPEC']._serialized_end=589
  _globals['_TEMPLATEREVISIONATTACHMENT']._serialized_start=591
  _globals['_TEMPLATEREVISIONATTACHMENT']._serialized_end=683
  _globals['_TEMPLATEREVISIONNAMESDETAIL']._serialized_start=686
  _globals['_TEMPLATEREVISIONNAMESDETAIL']._serialized_end=986
  _globals['_TEMPLATEREVISIONNAMESDETAIL_REVISION_NAMES']._serialized_start=876
  _globals['_TEMPLATEREVISIONNAMESDETAIL_REVISION_NAMES']._serialized_end=986
# @@protoc_insertion_point(module_scope)
