# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/app/app.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpkg/protocol/core/app/app.proto\x12\x05pbapp\x1a!pkg/protocol/core/base/base.proto\"\xb9\x01\n\x03\x41pp\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0e\n\x06\x62iz_id\x18\x02 \x01(\r\x12\x10\n\x08space_id\x18\x03 \x01(\t\x12\x15\n\rspace_type_id\x18\x04 \x01(\t\x12\x12\n\nspace_name\x18\x05 \x01(\t\x12\x17\n\x0fspace_type_name\x18\x06 \x01(\t\x12\x1c\n\x04spec\x18\x07 \x01(\x0b\x32\x0e.pbapp.AppSpec\x12\"\n\x08revision\x18\x08 \x01(\x0b\x32\x10.pbbase.Revision\"\\\n\x07\x41ppSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_type\x18\x02 \x01(\t\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\r\n\x05\x61lias\x18\x04 \x01(\t\x12\x11\n\tdata_type\x18\x05 \x01(\tBUZSgithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/app;pbappb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.app.app_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/app;pbapp'
  _globals['_APP']._serialized_start=78
  _globals['_APP']._serialized_end=263
  _globals['_APPSPEC']._serialized_start=265
  _globals['_APPSPEC']._serialized_end=357
# @@protoc_insertion_point(module_scope)
