# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/template/template.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)pkg/protocol/core/template/template.proto\x12\npbtemplate\x1a!pkg/protocol/core/base/base.proto\"\x96\x01\n\x08Template\x12\n\n\x02id\x18\x01 \x01(\r\x12&\n\x04spec\x18\x02 \x01(\x0b\x32\x18.pbtemplate.TemplateSpec\x12\x32\n\nattachment\x18\x03 \x01(\x0b\x32\x1e.pbtemplate.TemplateAttachment\x12\"\n\x08revision\x18\x04 \x01(\x0b\x32\x10.pbbase.Revision\"8\n\x0cTemplateSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04memo\x18\x03 \x01(\t\"?\n\x12TemplateAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x19\n\x11template_space_id\x18\x02 \x01(\rB_Z]github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/template;pbtemplateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.template.template_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z]github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/template;pbtemplate'
  _globals['_TEMPLATE']._serialized_start=93
  _globals['_TEMPLATE']._serialized_end=243
  _globals['_TEMPLATESPEC']._serialized_start=245
  _globals['_TEMPLATESPEC']._serialized_end=301
  _globals['_TEMPLATEATTACHMENT']._serialized_start=303
  _globals['_TEMPLATEATTACHMENT']._serialized_end=366
# @@protoc_insertion_point(module_scope)
