# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/client-query/client_query.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1pkg/protocol/core/client-query/client_query.proto\x12\x04pbcq\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"o\n\x0b\x43lientQuery\x12\n\n\x02id\x18\x01 \x01(\r\x12#\n\x04spec\x18\x02 \x01(\x0b\x32\x15.pbcq.ClientQuerySpec\x12/\n\nattachment\x18\x03 \x01(\x0b\x32\x1b.pbcq.ClientQueryAttachment\"\xdf\x01\n\x0f\x43lientQuerySpec\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x13\n\x0bsearch_type\x18\x02 \x01(\t\x12\x13\n\x0bsearch_name\x18\x03 \x01(\t\x12\x31\n\x10search_condition\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x15\x43lientQueryAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\rB]Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/client-query;pbcqb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.client_query.client_query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z[github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/client-query;pbcq'
  _globals['_CLIENTQUERY']._serialized_start=122
  _globals['_CLIENTQUERY']._serialized_end=233
  _globals['_CLIENTQUERYSPEC']._serialized_start=236
  _globals['_CLIENTQUERYSPEC']._serialized_end=459
  _globals['_CLIENTQUERYATTACHMENT']._serialized_start=461
  _globals['_CLIENTQUERYATTACHMENT']._serialized_end=516
# @@protoc_insertion_point(module_scope)
