# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/protocol/core/hook-revision/hook_revision.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bk_bscp.grpc_lib.core.base import base_pb2 as pkg_dot_protocol_dot_core_dot_base_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3pkg/protocol/core/hook-revision/hook_revision.proto\x12\x04pbhr\x1a!pkg/protocol/core/base/base.proto\"\x96\x01\n\x0cHookRevision\x12\n\n\x02id\x18\x01 \x01(\r\x12$\n\x04spec\x18\x02 \x01(\x0b\x32\x16.pbhr.HookRevisionSpec\x12\x30\n\nattachment\x18\x03 \x01(\x0b\x32\x1c.pbhr.HookRevisionAttachment\x12\"\n\x08revision\x18\x04 \x01(\x0b\x32\x10.pbbase.Revision\"N\n\x10HookRevisionSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0c\n\x04memo\x18\x04 \x01(\t\"9\n\x16HookRevisionAttachment\x12\x0e\n\x06\x62iz_id\x18\x01 \x01(\r\x12\x0f\n\x07hook_id\x18\x02 \x01(\rB^Z\\github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/hook-revision;pbhrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protocol.core.hook_revision.hook_revision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\\github.com/TencentBlueKing/bk-bcs/bcs-services/bcs-bscp/pkg/protocol/core/hook-revision;pbhr'
  _globals['_HOOKREVISION']._serialized_start=97
  _globals['_HOOKREVISION']._serialized_end=247
  _globals['_HOOKREVISIONSPEC']._serialized_start=249
  _globals['_HOOKREVISIONSPEC']._serialized_end=327
  _globals['_HOOKREVISIONATTACHMENT']._serialized_start=329
  _globals['_HOOKREVISIONATTACHMENT']._serialized_end=386
# @@protoc_insertion_point(module_scope)
